<template>
  <div class="body">
    <div class="content-title">Terms of content</div>
    <div class="content-info">
      This privacy statement forms part of the Fundobit Terms of Use ("Terms of Use"), hereinafter referred to as FDB. Unless otherwise
      specified in this privacy statement, the terms used in this privacy statement shall have the meaning specified in the terms of use.
    </div>
    <div class="content-info">
      This privacy statement explains how FDB collects, uses, process, disclose, share, transfer and protect your personal information
      obtained through FDB and its partners.<br />
      "We" here specifically refers to FDB and FDB operators. When collecting user-specified personal information, we are all based on the
      requirements of corresponding laws and regulations or government orders or our specific needs.
    </div>
    <div class="content-info">
      Please read the entire content of this privacy statement carefully. Once you visit FDB, regardless of whether you are registered or
      logged in to FDB, it means that you know, understand, and agree to all the terms in this privacy statement. If your information is
      used for other purposes not covered by this privacy statement or terms of use (including other FDB business rules), we will notify you
      in advance and obtain your consent.
    </div>
    <div class="content-title">1. What information do we collect？</div>
    <div class="content-info">The following are the types of information we collect when you register for FDB and use FDB services：</div>
    <div class="content-subtitle">1-1 Information required for registration：</div>
    <div class="content-info">
      When registering an FDB account, you need to provide your email address and name. In order to improve the security of your account,
      you can apply for secondary email verification. You need to provide your Google account name to open email verification.
    </div>
    <div class="content-subtitle">1-2 Information required for compliance with regulatory policies：</div>
    <div class="content-info">
      In order to comply with global industry regulatory standards, local regulatory standards and government orders, including anti-money
      laundering (AML), know-your-user (KYC), and counter-terrorism financing (CTF), when you use specific FDB services (such as digital
      asset trading related Service) before or during the process, in addition to identity information, we are required to collect identity
      documents (including passports, driver’s licenses, nationality IDs, state IDs, tax identification codes, passport numbers, driver’s
      license information, nationality identity Personal information ("supervisory information") such as certificate information and visa
      information), address proof, declaration of source of funds, source of wealth and other personal information ("supervisory
      information"), we will explain to you the content and requirements of such personal information each time we collect The right to
      change the content and requirements of information collection with changes in global industry regulatory standards, local regulatory
      standards, or government orders. This provision applies to FDB accounts of both individual and institutional users.
    </div>
    <div class="content-subtitle">1-3 Information required when using FDB service：</div>
    <div class="content-info">
      a. Service usage information<br />
      During your access to FDB and the use of FDB services, we will monitor and collect (including but not limited to) your visit date and
      time, device type and logo, operating system and related settings, browser and SIM card, and network operations Data related to
      business, IP address, GPS information, base station information, WLAN information, etc. ("Service Usage Information"). This
      information may be obtained directly from FDB or third-party service providers. The collection of data on the use of these services
      will help the system ensure that our interface is suitable for users on all platforms and can also provide support during criminal
      investigations.
    </div>
    <div class="content-info">
      b. Transaction information<br />
      For all corporate and personal accounts, we will collect various information ("transaction information") generated by transactions
      using FDB services, including account balance, transaction records (such as transaction initiation, payment method, transaction price,
      transaction quantity, transaction time, Withdrawal and authorization information, etc.), order activity and distribution records, etc.
      The collection of these data will be used to monitor suspicious transactions to prevent user fraud and assist in the judgment of legal
      cases, or other purposes disclosed in this privacy statement.
    </div>
    <div class="content-info">
      c. Communication information<br />
      You agree that we have the right to collect and use the information ("communication information") contained in or related to any
      communication you send to us or generated by using the FDB service for the purposes disclosed in this privacy statement. Communication
      information includes：<br />
      i. All messages, requests, or other information sent by you during your contact with FDB；<br />
      ii. All communications and file attachments are generated when you conduct transactions with other users or other data mainly
      generated through communications with other users.
    </div>
    <div class="content-info">
      d. Financial information<br />
      Agrees with your opinion, we collect and use the purposes disclosed in the privacy statement to collect and use the relevant financial
      information, transaction history, transaction data, or audit identification when you use the FDB service. It will be used to monitor
      online transaction behavior to prevent user behavior and smartphone instructions, or other purposes of this privacy statement.
    </div>
    <div class="content-title">2. How do we collect your information？</div>
    <div class="content-subtitle">2.1 Collect by yourself</div>
    <div class="content-info">
      You will directly provide us with the personal information we collect. In the following situations, we will collect and process your
      information：<br />
      a. sort of. When you register online, log in or access FDB, or use any FDB service；<br />
      b. When you do not complete any user surveys or provide feedback to us, by email or any other aspect；<br />
      c. When you use or browse our web pages or clients, through the cookies of your browser or software；<br />
      d. Other information collected by oneself mentioned in this privacy statement or terms of use (including other FDB business rules, the
      same below)。
    </div>
    <div class="content-subtitle">2.2 Self-obtained</div>
    <div class="content-info">
      We may be able to successfully obtain your information, but not the following：<br />
      a. sort of. Open databases, credit reporting agencies, and identity authentication partners；<br />
      b. Part of the chain data；<br />
      c. Marketing partners and distributors；<br />
      d. Advertising partners and data analysis.
    </div>
    <div class="content-subtitle">2.3 Anonymized and integrated data</div>
    <div class="content-info">
      Anonymization refers to the anonymization or modification of personal information, which can establish a data processing technology
      that cannot be associated with a specific individual. In addition to this article, any other provisions of this privacy policy are
      applicable to anonymized or merged personal data (referring to anonymized or merged personal data after the combination, no longer
      identifying or quoting a user's data).<br />
      We can use anonymous or integrated user data for any commercial purpose, including a better understanding of user needs and behaviors,
      improving our products and services, providing business intelligence and marketing, and detecting security threats. We may analyze it
      ourselves. To anonymize the data, it is also possible to use the provided analysis.
    </div>
    <div class="content-title">3. How do we use your information？</div>
    <div class="content-info">We use the information we collect for the following purposes or in the following ways：</div>
    <div class="content-subtitle">3.1 Provision and maintenance of services</div>
    <div class="content-info">
      We use the collected information to implement, maintain and provide better FDB services (including but not limited to processing
      various transactions), and to verify user identities.<br />
      We use your IP address and a unique identifier stored in cookies to verify your identity and behavior and provide FDB services. Due to
      legal obligations and system requirements, we are unable to provide you with all or part of FDB services in the absence of data such
      as identity information, regulatory information, service usage information, communication information, or transaction information.
    </div>
    <div class="content-subtitle">3.2 Protect users</div>
    <div class="content-info">
      We use the collected information to protect FDB's platform, user accounts, and files.<br />
      We use IP address and cookie data to prevent attacks such as spam, phishing, and distributed denial of service (DDoS).<br />
      We analyze transaction activity to detect suspicious behavior as early as possible and prevent fraud and the flow of funds to bad
      actors.
    </div>
    <div class="content-subtitle">3.3 Compliance with laws and regulations</div>
    <div class="content-info">
      Under the principle of respecting personal privacy and data security, we will use the collected information to fulfill statutory
      obligations, comply with government requirements and respond to reasonable requests from users. In cases where it is indeed necessary,
      such as to protect the significant interests of users or other natural persons, to perform public interest purposes, and to pursue our
      reasonable interests (but not to harm the interests of users), we may process your personal information without your consent. Except
      as stated in this privacy statement or the terms of use, we will not disclose or provide any personal information to third parties
      without the review of the legal team and/or the consent of the user.
    </div>
    <div class="content-subtitle">3.4 For measurement, research and development purposes</div>
    <div class="content-info">
      We analyze data to better understand how you use and interact with FDB services. Our operation team continuously conducts data
      analysis to ensure that the user experience is continuously optimized and solves various problems encountered in the use process in a
      timely manner. In addition, we use these data to customize, measure and improve the content and layout of FDB services, FDB websites,
      and applications, and to develop new services.<br />
      We continuously monitor system activity information and communications with users to find and quickly solve problems.
    </div>
    <div class="content-subtitle">3.5 Communicate with users</div>
    <div class="content-info">
      In order to communicate directly with users, we collect users' personal information, such as mobile phone numbers and email addresses,
      to provide users with support for work orders, or to notify users of information related to login, transaction, and account security
      in a timely manner. If we do not collect and process relevant personal information before communicating, we will not be able to
      respond to requests and questions submitted by users. All communications will be properly stored within FDB or the service provider
      designated by FDB and used to review the accuracy, keep it as evidence, or perform other legal or contractual obligations.
    </div>
    <div class="content-subtitle">3.6 Enforcement of terms of use and other agreements</div>
    <div class="content-info">
      The collected personal information will also be used for our continuous and active enforcement of the terms of use and other
      agreements reached with users, including but not limited to reviewing, investigating, and preventing any potentially prohibited or
      illegal activities that violate the terms of the foregoing agreement, or in accordance with Disclosure of relevant information to
      third parties with the authority stipulated in the foregoing agreement clauses.<br />
      We reserve the right to suspend or terminate the provision of any FDB services to any users who engage in activities that violate our
      terms of use or other agreements reached with users.
    </div>
    <div class="content-subtitle">3.7 Promote company acquisitions, mergers, or transactions</div>
    <div class="content-info">
      If necessary for company acquisitions, mergers, or other company transactions, we may process any information about your FDB account
      and use of FDB services.
    </div>
    <div class="content-subtitle">3.8 Marketing and Advertising</div>
    <div class="content-info">
      We may share your personal information with our marketing partners for use in targeting, modeling and/or analysis, and related
      marketing and advertising activities.
    </div>
    <div class="content-subtitle">3.9 Rebate</div>
    <div class="content-info">
      We may share the collected information with your referees, including but not limited to your identity information and transaction
      information, for a commission or other benefits.
    </div>
    <div class="content-subtitle">3.10 for any other purpose</div>
    <div class="content-info">We may disclose your personal information for any other purpose you agree to.</div>
    <div class="content-title">4. Marketing</div>
    <div class="content-info">
      If we think that you may like a certain FDB service or the products and services of our partners, we hope to push your information
      about those products or services.<br />
      If you agree to receive the above marketing information, you can choose to receive it at any time in the future.<br />
      You have the right to ask us at any time to stop contacting you for marketing purposes or pushing relevant information to you. If you
      do not want to be contacted for marketing purposes in the future, please click the unsubscribe link at the bottom of the marketing
      email to unsubscribe from marketing information.
    </div>
    <div class="content-title">5. How do we store and protect your information？</div>
    <div class="content-info">
      We store your personal information securely in a fault-tolerant secure storage space encrypted with industry standards, and take a
      number of security protection measures to insure that user information will not be lost, abused, or tampered with, including but not
      limited to：
    </div>
    <div class="content-subtitle">5.1 Physical measures</div>
    <div class="content-info">The physical data containing your personal information will be stored in a locked place.</div>
    <div class="content-subtitle">5.2 Electronic measures</div>
    <div class="content-info">
      Computer data containing your personal information will be stored on computer systems and storage media subject to strict login
      restrictions.
    </div>
    <div class="content-subtitle">5.3 Management measures</div>
    <div class="content-info">
      Only personnel authorized by us can access your personal information, and this personnel needs to abide by our internal rules for the
      confidentiality of personal information. We have also adopted strict office and file access restrictions.
    </div>
    <div class="content-subtitle">5.4 Technical measures</div>
    <div class="content-info">
      Use such as PCI scanning technology, secure socket layer encryption technology to transport and store your personal information, and
      use various current general security technologies and supporting management systems to reduce your personal information from being
      leaked, damaged, misused, and unauthorized access, The risk of unauthorized disclosure and modification.<br />
      5.5 Other measures Our web server is protected by a "firewall".<br />
      However, the above security protection measures cannot guarantee 100% information security. Therefore, we recommend that you
      understand and take independent security measures to protect the security of personal information. You agree that if any of your
      information leaks and other losses are caused by non-intentional or gross negligence, including but not limited to hacker attacks,
      power outages, or inevitable technical failures, to the maximum extent permitted by law, we Not liable.<br />
      If you suspect that your personal information, especially account or password information, has been leaked, please contact the FDB
      customer service team immediately.<br />
      Unless otherwise provided by laws and regulations, or otherwise provided in the terms of use, you agree and allow that we have the
      right but not the obligation to retain all the personal information we collect during the duration of your FDB account and within 5
      years after the account is closed record of.
    </div>
    <div class="content-title">6. Data Transmission</div>
    <div class="content-info">
      You know and understand that, in the following circumstances, we have the right to transfer or store all or part of the personal
      information collected to other countries and regions other than your country of nationality, country of habitual residence, or the
      country where the server is located, without your separate consent：
    </div>
    <div class="content-info">
      6.1 Based on the need to protect, process, analyze, and reasonably use personal information；<br />
      6.2 It is necessary to fulfill the terms of use or other agreements reached with the user；<br />
      6.3 Necessary based on the public interest；<br />
      6.4 Transmission is necessary for establishing, exercising, or defending the rights of us, our partners, or other users；or<br />
      6.5 Other circumstances required by law or government order.
    </div>
    <div class="content-title">7. Cookies</div>
    <div class="content-subtitle">7.1 What are Cookies？</div>
    <div class="content-info">
      Cookies are small amounts of data sent to your browser and stored on your computer's hard drive to collect standard Internet log
      information and visitor behavior information. When you visit FDB, we can automatically collect information from you through cookies or
      similar technologies.<br />
      For more information, please visit www.allaboutcookies.org.
    </div>
    <div class="content-subtitle">7.2 How do we use Cookies？</div>
    <div class="content-info">
      We use cookies in a variety of ways to improve your experience on our platform, including：<br />
      a. Keep your login；<br />
      b. Record your habits and preferences when browsing various items of FDB；<br />
      c. Use Google Stats through cookies to record our performance and check the effectiveness of online advertising.
    </div>
    <div class="content-subtitle">7.3 What cookies do we use？</div>
    <div class="content-info">We use many different types of cookies, mainly including (but not limited to)：</div>
    <div class="content-info">
      a. Functional cookies<br />
      We use these cookies so that we can recognize you on FDB and remember your previously selected preferences. These preferences may
      include your device, operating system, preferred language, location, and other session data. We use a mixture of first-party and
      third-party cookies.
    </div>
    <div class="content-info">
      b. Marketing cookies<br />
      We use these cookies to collect information about your visit to FDB, the content you view, the links you follow, and information about
      your browser, device, IP address, and referring URL. We sometimes share certain parts of data with third parties for marketing
      purposes. We can also share online data collected through cookies with our marketing partners. This means that when you visit another
      website, that website may show you ads based on your browsing patterns on FDB.
    </div>
    <div class="content-subtitle">7.4 How to manage cookies？</div>
    <div class="content-info">
      Most browsers are preset to accept cookies. You can choose to set your browser to not accept cookies, or notify you if cookies are
      installed. However, if it is set to prohibit cookies, you may not be able to activate or use certain functions of this platform.
    </div>
    <div class="content-title">8. What data protection rights do you have？</div>
    <div class="content-info">
      We want to ensure that you fully understand all your data protection rights. Unless otherwise provided by laws, regulations, or
      government orders, each user has the right to：
    </div>
    <div class="content-subtitle">8.1 Right of access</div>
    <div class="content-info">
      You have the right to request us to provide a copy of your personal data. We can charge you a small fee for providing this service.
    </div>
    <div class="content-subtitle">8.2 Right to rectification</div>
    <div class="content-info">
      You have the right to ask us to correct any information that you believe is inaccurate. You also have the right to ask us to fill in
      information that you think is incomplete within reasonable limits.
    </div>
    <div class="content-subtitle">8.3 Right to erasure</div>
    <div class="content-info">In some cases, you have the right to ask us to delete your personal data.</div>
    <div class="content-subtitle">8.4 Right to restrict processing</div>
    <div class="content-info">
      You have the right to request us to restrict the processing of your personal data under certain circumstances stipulated by law or
      especially prompted by us, but you know that restricting the processing of personal data may cause us to be unable to provide you with
      some FDB services.
    </div>
    <div class="content-subtitle">8.5 Right to refuse to process</div>
    <div class="content-info">
      You have the right to refuse us to process your personal data under certain circumstances stipulated by law or especially prompted by
      us, but you know that refusing to process personal data may cause us to be unable to provide you with some FDB services.
    </div>
    <div class="content-subtitle">8.6 The right to data portability</div>
    <div class="content-info">
      Under certain circumstances stipulated by law or especially prompted by us, you have the right to request that we transfer the data we
      collect to another organization or directly to you. We can charge you a small fee for providing this service.
    </div>
    <div class="content-title">9. Privacy policies of other websites</div>
    <div class="content-subtitle">9.1 Privacy policy outside the system</div>
    <div class="content-info">
      If you visit any link to other third-party platforms or partner websites or applications on FDB, you should agree to and abide by the
      separate and independent privacy policies of that third-party platform or partner. We are not responsible for the content and
      activities of these platforms or partners.
    </div>
    <div class="content-title">10. Revision of the Privacy Statement</div>
    <div class="content-info">
      We will adjust this privacy statement from time to time in accordance with changes in the law or our practice of collecting,
      processing, and using personal information. The revised announcement will be published on the FDB official website. You should check
      the privacy statement regularly and pay attention to its revisions. If you do not agree with the revised content, you should stop
      accessing it immediately. When an updated version of the privacy statement is released, your continued access means that you agree to
      the updated content and agree to abide by the updated privacy policy.
    </div>
    <div class="content-title">11. Contact us</div>
    <div class="content-info">
      FDB respects the freedom and rights of all users. If you have any questions or concerns about this privacy statement, or if you want
      to submit a data protection request, you can contact us on our support page.
    </div>
    <div class="content-bottom"></div>
  </div>
</template>

<script>
export default {
  name: 'PrivacyPolicyEN'
}
</script>
